//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_lam_viec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ca_lam_viec()
        {
            this.Phan_cong = new HashSet<Phan_cong>();
        }
    
        public int Ma_ca { get; set; }
        public string Ten_ca { get; set; }
        public System.TimeSpan Thoigianbatdau { get; set; }
        public System.TimeSpan Thoigianketthuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phan_cong> Phan_cong { get; set; }
    }
}
