//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoa_don
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoa_don()
        {
            this.Chi_tiet_hoa_don = new HashSet<Chi_tiet_hoa_don>();
        }
    
        public int Ma_HD { get; set; }
        public int Ma_NV { get; set; }
        public int Ma_KH { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
        public Nullable<System.DateTime> Ngay_mua { get; set; }
        public Nullable<double> Tong_tien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiet_hoa_don> Chi_tiet_hoa_don { get; set; }
        public virtual Khach_hang Khach_hang { get; set; }
        public virtual Tai_khoan Tai_khoan { get; set; }
    }
}
