//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_vien
    {
        public int Ma_NV { get; set; }
        public string Ten_NV { get; set; }
        public System.DateTime Ngay_sinh { get; set; }
        public bool Gioi_tinh { get; set; }
        public string SDT { get; set; }
        public Nullable<int> Luong { get; set; }
        public bool Trang_thai { get; set; }
    
        public virtual Tai_khoan Tai_khoan { get; set; }
    }
}
