//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phan_cong
    {
        public int Ma_NV { get; set; }
        public int Ma_ca { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    
        public virtual Ca_lam_viec Ca_lam_viec { get; set; }
        public virtual Tai_khoan Tai_khoan { get; set; }
    }
}
